---
# tasks file for roles/app
- name: Lauch Api
  docker_container:
    name: api
    image: yoannrobinet/tp-devops-cpe-api
    exposed_ports: 
      - 80:80
    state: started
    networks:
      - name: backNet
